### ISSUE TITLE
youtube refuses to connect on cloud-init.io site

### ISSUE THREAD

**Issue by gaughen** [canonical-web-and-design/cloud-init.io#111] opened 2019-08-29 19:50 UTC
## Summary

there appears to be a youtube video that is supposed to be on the top right of the front page, and it's not there.

## Process

Go to cloud-init.io, see the sad file icon on the right side of the top of the page.

## Screenshot

[if relevant, include a screenshot]

![image](https://user-images.githubusercontent.com/9114034/63971522-86911300-ca5b-11e9-9dbc-3cbccce8598c.png)

**Comment by anthonydillon** [comment] 2019-08-30 08:20
Thanks, this is a duplicate of #109

**Closed by anthonydillon** 2019-08-30 08:20 UTC
Labels: Duplicate, Priority: High
